CREATE TABLE "UNIVERSITIES" (
  "ID" serial PRIMARY KEY,
  "NAME" varchar UNIQUE,
  "CITY" varchar,
  "COUNTRY" varchar
);

CREATE TABLE "DEPARTMENTS" (
  "ID" serial PRIMARY KEY,
  "FACULTY" varchar,
  "NAME" varchar,
  unique ("FACULTY","NAME")
);

CREATE TABLE "STUDENTS" (
  "ID" serial PRIMARY KEY,
  "EMAIL" varchar UNIQUE,
  "PASSWORD" text,
  "NAME" varchar,
  "DEPARTMANT" int,
  "UNIVERSTY" int,
  "CITY" int
);

CREATE TABLE "CITIES" (
  "ID" serial UNIQUE,
  "COUNTRY" varchar,
  "NAME" varchar,
  PRIMARY KEY ("COUNTRY", "NAME")
);

CREATE TABLE "STUDENT_SKILL" (
  "ID" serial,
  "STU_ID" int,
  "SKILL_ID" int,
  PRIMARY KEY ("STU_ID", "SKILL_ID")
);

CREATE TABLE "COMPANIES" (
  "ID" serial PRIMARY KEY,
  "EMAIL" varchar UNIQUE,
  "PASSWORD" text,
  "NAME" varchar UNIQUE,
  "CITY" int,
  "EXC_ID" int,
  "EXC_NAME" varchar,
  "EXC_DOB" date
);

CREATE TABLE "JOB_LISTINGS" (
  "ID" serial PRIMARY KEY,
  "COMPANY" int,
  "DESCRIPTION" varchar,
  "LOCATION" int
);

CREATE TABLE "JOB_REQ" (
  "ID" serial,
  "JOB_ID" int,
  "REQ_ID" int,
  PRIMARY KEY ("JOB_ID", "REQ_ID")
);

CREATE TABLE "SKILLS" (
  "ID" serial PRIMARY KEY,
  "NAME" varchar UNIQUE,
  "DESCRIPTION" varchar
);

CREATE TABLE "APLICATIONS" (
  "JOB_ID" int,
  "STU_ID" int,
  "DIRECTION" boolean,
  "RESPONSE" boolean
);

ALTER TABLE "STUDENTS" ADD FOREIGN KEY ("DEPARTMANT") REFERENCES "DEPARTMENTS" ("ID");

ALTER TABLE "STUDENTS" ADD FOREIGN KEY ("UNIVERSTY") REFERENCES "UNIVERSITIES" ("ID");

ALTER TABLE "STUDENTS" ADD FOREIGN KEY ("CITY") REFERENCES "CITIES" ("ID");

ALTER TABLE "STUDENT_SKILL" ADD FOREIGN KEY ("STU_ID") REFERENCES "STUDENTS" ("ID");

ALTER TABLE "STUDENT_SKILL" ADD FOREIGN KEY ("SKILL_ID") REFERENCES "SKILLS" ("ID");

ALTER TABLE "COMPANIES" ADD FOREIGN KEY ("CITY") REFERENCES "CITIES" ("ID");

ALTER TABLE "JOB_LISTINGS" ADD FOREIGN KEY ("COMPANY") REFERENCES "COMPANIES" ("ID");

ALTER TABLE "JOB_LISTINGS" ADD FOREIGN KEY ("LOCATION") REFERENCES "CITIES" ("ID");

ALTER TABLE "JOB_REQ" ADD FOREIGN KEY ("JOB_ID") REFERENCES "JOB_LISTINGS" ("ID");

ALTER TABLE "JOB_REQ" ADD FOREIGN KEY ("REQ_ID") REFERENCES "SKILLS" ("ID");

ALTER TABLE "APLICATIONS" ADD FOREIGN KEY ("JOB_ID") REFERENCES "JOB_LISTINGS" ("ID");

ALTER TABLE "APLICATIONS" ADD FOREIGN KEY ("STU_ID") REFERENCES "STUDENTS" ("ID");

